### ISSUE TITLE
Why'd you block me?

### ISSUE THREAD

**Issue by pauldotknopf** [bnb/bnb.im#4]
https://twitter.com/pauldotknopf/status/1190883179080630272?s=20

Seems weird to be blocked with having no interaction, and your title being a "developer advocate" at Microsoft.

**Comment by bnb** [comment]
seems weird to open issues on someone's personal site asking why you're blocked rather than just walking away.

looking through your twitter profile, *after* I blocked you you retweeted an absurd tweet of Bob Martin's and debated trans women on whether or not they should disclose. The block was probably because of your engagement in [this](https://twitter.com/pauldotknopf/status/1187101647488589829?s=20) thread.

Issue solved, please don't talk to me anymore :)
